"""EMA shadow policy for stable local rollouts."""

from __future__ import annotations

from typing import Any

import torch

from hermes_agentic_rl.backends.base import LLMBackend


class EMAModel:
    """Exponential moving average of policy parameters.

    The shadow backend is frozen and intended for rollout generation only; the
    learner policy remains the only object used for scoring and gradients.
    """

    def __init__(
        self,
        policy: LLMBackend,
        tau: float = 0.005,
        *,
        tau_start: float | None = None,
        tau_warmup_steps: int = 0,
    ) -> None:
        if not hasattr(policy, "clone_frozen"):
            raise TypeError("EMA rollout requires backend.clone_frozen()")
        if not hasattr(policy, "model"):
            raise TypeError("EMA rollout requires backend.model")
        self.shadow: LLMBackend = policy.clone_frozen()  # type: ignore[attr-defined]
        self.tau = float(tau)
        if self.tau <= 0.0 or self.tau > 1.0:
            raise ValueError("ema_tau must be in (0, 1]")
        # Optional warm-up: early in training the learner moves fast, but a
        # tiny tau (e.g. 0.005) leaves the shadow far behind, so rollouts are
        # generated by a stale policy. Linearly anneal tau from ``tau_start``
        # down to ``tau`` over ``tau_warmup_steps`` updates so the shadow
        # tracks the learner quickly at first.
        self.tau_warmup_steps = int(max(0, tau_warmup_steps))
        if tau_start is None:
            self.tau_start = self.tau
        else:
            self.tau_start = float(tau_start)
            if self.tau_start <= 0.0 or self.tau_start > 1.0:
                raise ValueError("ema_tau_start must be in (0, 1]")
        self._updates = 0

    def current_tau(self) -> float:
        """Scheduled blend factor for the next update."""
        if self.tau_warmup_steps <= 0 or self._updates >= self.tau_warmup_steps:
            return self.tau
        frac = self._updates / self.tau_warmup_steps
        return self.tau_start + frac * (self.tau - self.tau_start)

    @torch.no_grad()
    def update(self, policy: LLMBackend) -> None:
        """Blend learner parameters into the frozen shadow backend."""
        self._tau_now = self.current_tau()
        self._update_module(self.shadow.model, policy.model)  # type: ignore[attr-defined]
        shadow_head = getattr(self.shadow, "value_head", None)
        policy_head = getattr(policy, "value_head", None)
        if shadow_head is not None and policy_head is not None:
            self._update_module(shadow_head, policy_head)
        self._updates += 1

    def as_rollout_backend(self) -> LLMBackend:
        return self.shadow

    def _update_module(self, shadow_module: Any, source_module: Any) -> None:
        tau = getattr(self, "_tau_now", self.tau)
        source_params = dict(source_module.named_parameters())
        for name, shadow_param in shadow_module.named_parameters():
            source_param = source_params.get(name)
            if source_param is None:
                continue
            shadow_param.data.mul_(1.0 - tau).add_(
                source_param.detach().to(
                    device=shadow_param.device,
                    dtype=shadow_param.dtype,
                ),
                alpha=tau,
            )

        source_buffers = dict(source_module.named_buffers())
        for name, shadow_buffer in shadow_module.named_buffers():
            source_buffer = source_buffers.get(name)
            if source_buffer is None or shadow_buffer.shape != source_buffer.shape:
                continue
            shadow_buffer.copy_(
                source_buffer.detach().to(
                    device=shadow_buffer.device,
                    dtype=shadow_buffer.dtype,
                )
            )
